version: "1",
name: "gamelog"
services:
  frontend:
    container_name: "gamelogfront"
    image: "gw0zdziu/gamelog:front"
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - backend
  backend:
    container_name: "gamelogback"
    image: "gw0zdziu/gamelog:back"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend
      - frontend
    depends_on:
      - database
  database:
    image: "postgres"
    container_name: "gamelogdb-dev"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: gamelogdb
      POSTGRES_DB: gamelogdb
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

